DROP TABLE IF EXISTS `ps_smart_blog_post_lang`;
CREATE TABLE `ps_smart_blog_post_lang` (
  `id_smart_blog_post` int(11) NOT NULL,
  `id_lang` varchar(45) NOT NULL DEFAULT '',
  `meta_title` varchar(150) DEFAULT NULL,
  `meta_keyword` varchar(200) DEFAULT NULL,
  `meta_description` varchar(450) DEFAULT NULL,
  `short_description` varchar(450) DEFAULT NULL,
  `content` text,
  `link_rewrite` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id_smart_blog_post`,`id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Scheme for table ps_smart_blog_post_lang */
INSERT INTO `ps_smart_blog_post_lang` VALUES
('2','1','Designer`s look',NULL,'Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility.','Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility. And it is good for you because as we all know people change their claims with the course of time, and our good will be\r\nactual for a long time.','<p>Cras in sem in arcu ultrices egestas sit amet nec metus. Suspendisse magna nisi, cursus ut condimentum eu, dapibus at dolor. Sed venenatis sapien quis urna consequat, quis tempor neque porttitor. Vivamus iaculis eleifend varius. Vestibulum quis justo massa. Mauris et eros mollis, placerat mauris nec, mattis purus.</p>','Designer`s-look'),
('2','2','Designer`s look',NULL,'Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility.','Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility. And it is good for you because as we all know people change their claims with the course of time, and our good will be\r\nactual for a long time.','<p>Cras in sem in arcu ultrices egestas sit amet nec metus. Suspendisse magna nisi, cursus ut condimentum eu, dapibus at dolor. Sed venenatis sapien quis urna consequat, quis tempor neque porttitor. Vivamus iaculis eleifend varius. Vestibulum quis justo massa. Mauris et eros mollis, placerat mauris nec, mattis purus.</p>','Designer`s-look'),
('2','3','Designer`s look',NULL,'Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility.','Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility. And it is good for you because as we all know people change their claims with the course of time, and our good will be\r\nactual for a long time.','<p>Cras in sem in arcu ultrices egestas sit amet nec metus. Suspendisse magna nisi, cursus ut condimentum eu, dapibus at dolor. Sed venenatis sapien quis urna consequat, quis tempor neque porttitor. Vivamus iaculis eleifend varius. Vestibulum quis justo massa. Mauris et eros mollis, placerat mauris nec, mattis purus.</p>','Designer`s-look'),
('2','4','Designer`s look',NULL,'Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility.','Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility. And it is good for you because as we all know people change their claims with the course of time, and our good will be\r\nactual for a long time.','<p>Cras in sem in arcu ultrices egestas sit amet nec metus. Suspendisse magna nisi, cursus ut condimentum eu, dapibus at dolor. Sed venenatis sapien quis urna consequat, quis tempor neque porttitor. Vivamus iaculis eleifend varius. Vestibulum quis justo massa. Mauris et eros mollis, placerat mauris nec, mattis purus.</p>','Designer`s-look'),
('2','5','Designer`s look',NULL,'Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility.','Our product is universal because it suits different customers with different demands. We assure you\r\nit is really important, it shows that our good has\r\nsuch capacity as flexibility. And it is good for you because as we all know people change their claims with the course of time, and our good will be\r\nactual for a long time.','<p>Cras in sem in arcu ultrices egestas sit amet nec metus. Suspendisse magna nisi, cursus ut condimentum eu, dapibus at dolor. Sed venenatis sapien quis urna consequat, quis tempor neque porttitor. Vivamus iaculis eleifend varius. Vestibulum quis justo massa. Mauris et eros mollis, placerat mauris nec, mattis purus.</p>','Designer`s-look'),
('3','1','New collection',NULL,'Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others.','Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a\r\nlot of money. But nowadays fashion is not that\r\nunavailable as it was a couple of centuries ago.\r\nWe are lucky to have an opportunity to buy\r\nqualitative, fashionable and affordable clothes.','<p>Fashion is the detector of prosperity and social <br />rank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a <br />lot of money. But nowadays fashion is not that <br />unavailable as it was a couple of centuries ago. <br />We are lucky to have an opportunity to buy <br />qualitative, fashionable and affordable clothes.</p>','New-collection'),
('3','2','New collection',NULL,'Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others.','Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a\r\nlot of money. But nowadays fashion is not that\r\nunavailable as it was a couple of centuries ago.\r\nWe are lucky to have an opportunity to buy\r\nqualitative, fashionable and affordable clothes.','<p>Fashion is the detector of prosperity and social <br />rank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a <br />lot of money. But nowadays fashion is not that <br />unavailable as it was a couple of centuries ago. <br />We are lucky to have an opportunity to buy <br />qualitative, fashionable and affordable clothes.</p>','New-collection'),
('3','3','New collection',NULL,'Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others.','Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a\r\nlot of money. But nowadays fashion is not that\r\nunavailable as it was a couple of centuries ago.\r\nWe are lucky to have an opportunity to buy\r\nqualitative, fashionable and affordable clothes.','<p>Fashion is the detector of prosperity and social <br />rank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a <br />lot of money. But nowadays fashion is not that <br />unavailable as it was a couple of centuries ago. <br />We are lucky to have an opportunity to buy <br />qualitative, fashionable and affordable clothes.</p>','New-collection'),
('3','4','New collection',NULL,'Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others.','Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a\r\nlot of money. But nowadays fashion is not that\r\nunavailable as it was a couple of centuries ago.\r\nWe are lucky to have an opportunity to buy\r\nqualitative, fashionable and affordable clothes.','<p>Fashion is the detector of prosperity and social <br />rank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a <br />lot of money. But nowadays fashion is not that <br />unavailable as it was a couple of centuries ago. <br />We are lucky to have an opportunity to buy <br />qualitative, fashionable and affordable clothes.</p>','New-collection'),
('3','5','New collection',NULL,'Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others.','Fashion is the detector of prosperity and social\r\nrank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a\r\nlot of money. But nowadays fashion is not that\r\nunavailable as it was a couple of centuries ago.\r\nWe are lucky to have an opportunity to buy\r\nqualitative, fashionable and affordable clothes.','<p>Fashion is the detector of prosperity and social <br />rank. So, our natural desire to wear fashionable clothes has many reasons such as historical, social and others. Therefore being fashionable costs a <br />lot of money. But nowadays fashion is not that <br />unavailable as it was a couple of centuries ago. <br />We are lucky to have an opportunity to buy <br />qualitative, fashionable and affordable clothes.</p>','New-collection'),
('4','1','Create a style',NULL,'Fashion has always been so temporary and\r\nuncertain. ','Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.','<p>Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.</p>','Create-a-style'),
('4','2','Create a style',NULL,'Fashion has always been so temporary and\r\nuncertain. ','Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.','<p>Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.</p>','Create-a-style'),
('4','3','Create a style',NULL,'Fashion has always been so temporary and\r\nuncertain. ','Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.','<p>Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.</p>','Create-a-style'),
('4','4','Create a style',NULL,'Fashion has always been so temporary and\r\nuncertain. ','Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.','<p>Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.</p>','Create-a-style'),
('4','5','Create a style',NULL,'Fashion has always been so temporary and\r\nuncertain. ','Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.','<p>Fashion has always been so temporary and uncertain. You can’t keep up with it.  This social phenomenon is very whimsical, thus we as the consumers always try to stay in touch with all the latest fashion tendencies. Obviously there is nothing wrong about it because fashion satisfies our willingness to be attractive.</p>','Create-a-style');
