DROP TABLE IF EXISTS `ps_tmhtmlcontent`;
CREATE TABLE `ps_tmhtmlcontent` (
  `id_item` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_shop` int(10) unsigned NOT NULL,
  `id_lang` int(10) unsigned NOT NULL,
  `item_order` int(10) unsigned NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `title_use` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `hook` varchar(100) DEFAULT NULL,
  `url` text,
  `target` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `image` varchar(100) DEFAULT NULL,
  `image_w` varchar(10) DEFAULT NULL,
  `image_h` varchar(10) DEFAULT NULL,
  `html` text,
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_item`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

/* Scheme for table ps_tmhtmlcontent */
INSERT INTO `ps_tmhtmlcontent` VALUES
('3','1','1','1',NULL,'0','topColumn',NULL,'0',NULL,'0','0','<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">NAVIGATION</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-shopping232\"></span>\r\n<p>Easy to use navigationwith drop-down<br> menus on the Catalog page</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-set6\"></span>\r\n<p>Keyword search field to help<br> customers navigate collections</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-front16\"></span>\r\n<p>Automatic pagination of product<br> listings</p>\r\n</li>\r\n</ul>\r\n</div>\r\n<div class=\"right_img_item\">\r\n<img src=\"img/cms/banner_2.jpg\" class=\"item-img\" title=\"\" alt=\"\" width=\"100%\" height=\"100%\" />\r\n</div>','1'),
('4','1','1','2',NULL,'0','topColumn',NULL,'0',NULL,'0','0','<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">Product Page</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>In Stock and Out of Stock notifications</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Built in Facebook, Twitter and Google Plus sharing for each product</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Ability to search more products by tag and by collection</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Product recommendations on each product page and on the checkout page when the cart is empty.</p>\r\n</li>\r\n</ul>\r\n</div>','1'),
('6','1','2','1',NULL,'0','topColumn',NULL,'0',NULL,NULL,NULL,'<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">NAVIGATION</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-shopping232\"></span>\r\n<p>Easy to use navigationwith drop-down<br> menus on the Catalog page</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-set6\"></span>\r\n<p>Keyword search field to help<br> customers navigate collections</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-front16\"></span>\r\n<p>Automatic pagination of product<br> listings</p>\r\n</li>\r\n</ul>\r\n</div>\r\n<div class=\"right_img_item\">\r\n<img src=\"img/cms/banner_2.jpg\" class=\"item-img\" title=\"\" alt=\"\" width=\"100%\" height=\"100%\" />\r\n</div>','1'),
('7','1','3','1',NULL,'0','topColumn',NULL,'0',NULL,NULL,NULL,'<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">NAVIGATION</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-shopping232\"></span>\r\n<p>Easy to use navigationwith drop-down<br> menus on the Catalog page</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-set6\"></span>\r\n<p>Keyword search field to help<br> customers navigate collections</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-front16\"></span>\r\n<p>Automatic pagination of product<br> listings</p>\r\n</li>\r\n</ul>\r\n</div>\r\n<div class=\"right_img_item\">\r\n<img src=\"img/cms/banner_2.jpg\" class=\"item-img\" title=\"\" alt=\"\" width=\"100%\" height=\"100%\" />\r\n</div>','1'),
('8','1','4','1',NULL,'0','topColumn',NULL,'0',NULL,NULL,NULL,'<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">NAVIGATION</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-shopping232\"></span>\r\n<p>Easy to use navigationwith drop-down<br> menus on the Catalog page</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-set6\"></span>\r\n<p>Keyword search field to help<br> customers navigate collections</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-front16\"></span>\r\n<p>Automatic pagination of product<br> listings</p>\r\n</li>\r\n</ul>\r\n</div>\r\n<div class=\"right_img_item\">\r\n<img src=\"img/cms/banner_2.jpg\" class=\"item-img\" title=\"\" alt=\"\" width=\"100%\" height=\"100%\" />\r\n</div>','1'),
('9','1','5','1',NULL,'0','topColumn',NULL,'0',NULL,NULL,NULL,'<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">NAVIGATION</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-shopping232\"></span>\r\n<p>Easy to use navigationwith drop-down<br> menus on the Catalog page</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-set6\"></span>\r\n<p>Keyword search field to help<br> customers navigate collections</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-front16\"></span>\r\n<p>Automatic pagination of product<br> listings</p>\r\n</li>\r\n</ul>\r\n</div>\r\n<div class=\"right_img_item\">\r\n<img src=\"img/cms/banner_2.jpg\" class=\"item-img\" title=\"\" alt=\"\" width=\"100%\" height=\"100%\" />\r\n</div>','1'),
('10','1','2','2',NULL,'0','topColumn',NULL,'0',NULL,'0','0','<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">Product Page</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>In Stock and Out of Stock notifications</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Built in Facebook, Twitter and Google Plus sharing for each product</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Ability to search more products by tag and by collection</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Product recommendations on each product page and on the checkout page when the cart is empty.</p>\r\n</li>\r\n</ul>\r\n</div>','1'),
('11','1','3','2',NULL,'0','topColumn',NULL,'0',NULL,'0','0','<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">Product Page</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>In Stock and Out of Stock notifications</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Built in Facebook, Twitter and Google Plus sharing for each product</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Ability to search more products by tag and by collection</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Product recommendations on each product page and on the checkout page when the cart is empty.</p>\r\n</li>\r\n</ul>\r\n</div>','1'),
('12','1','4','2',NULL,'0','topColumn',NULL,'0',NULL,'0','0','<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">Product Page</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>In Stock and Out of Stock notifications</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Built in Facebook, Twitter and Google Plus sharing for each product</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Ability to search more products by tag and by collection</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Product recommendations on each product page and on the checkout page when the cart is empty.</p>\r\n</li>\r\n</ul>\r\n</div>','1'),
('13','1','5','2',NULL,'0','topColumn',NULL,'0',NULL,'0','0','<div class=\"left_img_item\">\r\n<h4 class=\"title_item\">Product Page</h4>\r\n\r\n<ul class=\"items_list\">\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>In Stock and Out of Stock notifications</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Built in Facebook, Twitter and Google Plus sharing for each product</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Ability to search more products by tag and by collection</p>\r\n</li>\r\n<li>\r\n<span class=\"material-design-keyboard53\"></span>\r\n<p>Product recommendations on each product page and on the checkout page when the cart is empty.</p>\r\n</li>\r\n</ul>\r\n</div>','1');
